### ISSUE TITLE
Issue with c-ares build on Mac OS Sonoma 14.5 , as part of Milvus Build.

### ISSUE THREAD

**Issue by rohitreddy1698** [c-ares/c-ares#892]
Hi,

I am trying to build Milvus on Mac OS Sonoma 14.5 , as part of the third party dependency build it is trying to build c-ares and is failing with the following error :

```
.
.
[ 88%] Building C object src/lib/CMakeFiles/c-ares.dir/util/ares_rand.c.o
[ 89%] Building C object src/lib/CMakeFiles/c-ares.dir/util/ares__iface_ips.c.o
[ 90%] Building C object src/lib/CMakeFiles/c-ares.dir/util/ares__timeval.c.o
In file included from /Users/rohitmothe/.conan/data/c-ares/1.33.0/_/_/build/65d0c6387c314520223dd15a4a7aadd3107d2214/src/src/lib/ares_sysconfig_mac.c:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkConfiguration.h:31:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:126:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:196:6: error: unknown type name 'AuthorizationRef'
                                        AuthorizationRef        __nullable      authorization
                                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:196:23: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'int'
                                        AuthorizationRef        __nullable      authorization
                                                                ^
<built-in>:337:20: note: expanded from here
#define __nullable _Nullable
                   ^
2 errors generated.
make[3]: *** [src/lib/CMakeFiles/c-ares.dir/ares_sysconfig_mac.c.o] Error 1
make[2]: *** [src/lib/CMakeFiles/c-ares.dir/all] Error 2
make[1]: *** [all] Error 2
c-ares/1.33.0: 
c-ares/1.33.0: ERROR: Package '65d0c6387c314520223dd15a4a7aadd3107d2214' build failed
c-ares/1.33.0: WARN: Build folder /Users/rohitmothe/.conan/data/c-ares/1.33.0/_/_/build/65d0c6387c314520223dd15a4a7aadd3107d2214/build/Release
ERROR: c-ares/1.33.0: Error in build() method, line 63
	cmake.build()
	ConanException: Error 2 while executing cmake --build "/Users/rohitmothe/.conan/data/c-ares/1.33.0/_/_/build/65d0c6387c314520223dd15a4a7aadd3107d2214/build/Release" '--' '-j14'
conan install failed
make: *** [build-3rdparty] Error 1
```

This is my configuration for cmake, make and other library versions :

```
(tls_venv) ➜  milvus git:(master) cmake --version
cmake version 3.30.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(tls_venv) ➜  milvus git:(master) make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
(tls_venv) ➜  milvus git:(master) gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(tls_venv) ➜  milvus git:(master) go version
go version go1.23.1 darwin/arm64
(tls_venv) ➜  milvus git:(master) python3 version
/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python
(tls_venv) ➜  milvus git:(master) 
(tls_venv) ➜  milvus git:(master) 

(tls_venv) ➜  milvus git:(master) pip show conan
Name: conan
Version: 1.61.0
Summary: Conan C/C++ package manager
Home-page: https://conan.io
Author: JFrog LTD
Author-email: luism@jfrog.com
License: MIT
Location: /Users/rohitmothe/Desktop/milvus-kafka-mtls/tls_venv/lib/python3.11/site-packages
Requires: bottle, colorama, fasteners, Jinja2, node-semver, patch-ng, pluginbase, pygments, PyJWT, python-dateutil, PyYAML, requests, six, tqdm, urllib3
Required-by: 
(tls_venv) ➜  milvus git:(master) 

(tls_venv) ➜  milvus git:(master) uname -m
arm64
(tls_venv) ➜  milvus git:(master) ulimit
unlimited

(tls_venv) ➜  milvus git:(master) conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=15
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
(tls_venv) ➜  milvus git:(master) 

just to be sure I installed the xsltproc as well : 
(tls_venv) ➜  milvus git:(master) which xsltproc
/opt/homebrew/anaconda3/bin/xsltproc
```

However from the logs I suspect this is related to a compatibility issue between my environment and the version of c-ares I am using.

**Comment by bradh352** [comment]
As far as I can tell this is something wrong with your system.  Your build error is coming from a MacOS internal header, not from anything related to c-ares.  Our CI system builds and tests each commit on MacOS and isn't reporting any sort of issues, see latest build here: https://github.com/c-ares/c-ares/actions/runs/11051153050/job/30700442371

The only other thing I could see is if you're using some odd cflag that alters behavior.  I'm not familiar with conan, so you might reach out to those guys since it appears that's what's doing the building of c-ares.  Also the current release is 1.33.1 not sure why you're building 1.33.0.  I just googled and conan appears to have 1.33.1 available.

**Comment by rohitreddy1698** [comment]
Hi @bradh352 , thanks a lot for replying on this.

So this is being built as part of Milvus - an Open Source Vector Library - https://github.com/milvus-io/milvus
This has 1.33.0 in its stable release as a transitive dependency. ( meaning it is dependent on a package which is dependent on c-ares )

Thats right conan is downloading and building the dependencies.
And I agree it might be a error with my system and I was looking to see if I could get some help related to why it was failing or what I am missing in my env.

Let me try with 1.33.1

Thanks,
Rohit Mothe

**Comment by bradh352** [comment]
i'll try building milvus myself for the heck of it, but I'm on MacOS 15 so I don't know how much use it will be.

**Comment by bradh352** [comment]
the build for milvus just seems to not be great.  I had to downgrade to conan v1 because v2 threw an unknown arg when running make.    But then it says to use conan v2 when building.  Anyhow, I did reproduce your same error when running the milvus build.

**Comment by rohitreddy1698** [comment]
the build for milvus just seems to not be great - agree a lot of issues with it.
But then it says to use conan v2 when building - From what I have understood conan v1 ( 1.61.0 ) is the version to be used.

Anyhow, I did reproduce your same error when running the milvus build. - Okay great ( or should I say not :/ ) , I have tried adding 1.33.1 as an explicit dependency and trying to resolve this issue by fixing my Mac configs as well, since the issue seems to be stemming from there.

Please do let me know if you are able to get over this, and I will do the same.

Thanks

**Comment by bradh352** [comment]
I just reproduced outside of conan and milvus, the problem is something with homebrew's llvm 15 and apple's headers.  Apple's compiler works, llvm16 from homebrew works, llvm19 from homebrew works.

**Comment by bradh352** [comment]
I'm going to consider this closed since either its something wrong with llvm15 and apple in general or something up with homebrew.  Anything that needs to use Authorization.h will fail.
