### ISSUE TITLE
error: implicit declaration of function 'fcntl' [-Werror,-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by ryandesign** [c-ares/c-ares#782]
1.30.0 fails to build on [Mac OS X 10.7](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/194812/steps/install-port/logs/stdio):

```
src/lib/ares_event_configchg.c:370:11: error: implicit declaration of function 'fcntl' [-Werror,-Wimplicit-function-declaration]
  flags = fcntl((*configchg)->fd, F_GETFL, 0);
          ^
src/lib/ares_event_configchg.c:370:35: error: use of undeclared identifier 'F_GETFL'
  flags = fcntl((*configchg)->fd, F_GETFL, 0);
                                  ^
src/lib/ares_event_configchg.c:371:27: error: use of undeclared identifier 'F_SETFL'
  fcntl((*configchg)->fd, F_SETFL, flags | O_NONBLOCK);
                          ^
3 errors generated.
```

And [on Mac OS X 10.6](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/205928/steps/install-port/logs/stdio):

```
src/lib/ares_event_configchg.c:370:11: error: implicit declaration of function 'fcntl' [-Werror,-Wimplicit-function-declaration]
  flags = fcntl((*configchg)->fd, F_GETFL, 0);
          ^
src/lib/ares_event_configchg.c:370:35: error: use of undeclared identifier 'F_GETFL'
  flags = fcntl((*configchg)->fd, F_GETFL, 0);
                                  ^
src/lib/ares_event_configchg.c:371:44: error: use of undeclared identifier 'O_NONBLOCK'
  fcntl((*configchg)->fd, F_SETFL, flags | O_NONBLOCK);
                                           ^
src/lib/ares_event_configchg.c:371:27: error: use of undeclared identifier 'F_SETFL'
  fcntl((*configchg)->fd, F_SETFL, flags | O_NONBLOCK);
                          ^
4 errors generated.
```

`fcntl` is defined in <fcntl.h> but you don't appear to have `#include`d that header in ares_event_configchg.c.

**Comment by barracuda156** [comment]
@ryandesign You are right about including `<fcntl.h>`.

But then it bumps into non-existing `os/availability.h`, and once that is removed, it breaks on:
```
:info:build cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/build/src/lib && /usr/bin/gcc-4.2 -DCARES_BUILDING_LIBRARY -DHAVE_CONFIG_H=1 -D_DARWIN_C_SOURCE -Dc_ares_EXPORTS -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/build -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0 -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib -pipe -Os -DNDEBUG -I/opt/local/include -Wall -Wextra -Wcast-align -Wconversion -Wdeclaration-after-statement -Wfloat-equal -Wformat-security -Winit-self -Wmissing-braces -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-overflow -Wstrict-prototypes -Wundef -Wunused -Wvariadic-macros -Wwrite-strings -Werror=implicit-int -Werror=implicit-function-declaration -Qunused-arguments -std=gnu89 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT src/lib/CMakeFiles/c-ares.dir/ares_sysconfig_mac.c.o -MF CMakeFiles/c-ares.dir/ares_sysconfig_mac.c.o.d -o CMakeFiles/c-ares.dir/ares_sysconfig_mac.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/ares_sysconfig_mac.c
:info:build In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/ares_sysconfig_mac.c:54:
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:114: warning: no previous prototype for ‘dns_configuration_notify_key’
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h: In function ‘dns_configuration_notify_key’:
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:114: error: expected declaration specifiers before ‘API_AVAILABLE’
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:117: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘API_AVAILABLE’
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:120: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘API_AVAILABLE’
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:124: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘API_AVAILABLE’
:info:build In file included from /usr/include/math.h:26,
:info:build                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:19,
:info:build                  from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkConfiguration.h:30,
:info:build                  from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/ares_sysconfig_mac.c:55:
:info:build /usr/include/architecture/ppc/math.h:65: error: storage class specified for parameter ‘float_t’
:info:build /usr/include/architecture/ppc/math.h:66: error: storage class specified for parameter ‘double_t’
:info:build /usr/include/architecture/ppc/math.h:128: error: storage class specified for parameter ‘__math_errhandling’
:info:build /usr/include/architecture/ppc/math.h:149: error: storage class specified for parameter ‘__fpclassifyf’
:info:build /usr/include/architecture/ppc/math.h:150: error: storage class specified for parameter ‘__fpclassifyd’
:info:build /usr/include/architecture/ppc/math.h:151: error: storage class specified for parameter ‘__fpclassify’
:info:build /usr/include/architecture/ppc/math.h:188: error: storage class specified for parameter ‘__inline_isfinitef’
:info:build /usr/include/architecture/ppc/math.h:189: error: storage class specified for parameter ‘__inline_isfinited’
:info:build /usr/include/architecture/ppc/math.h:190: error: storage class specified for parameter ‘__inline_isfinite’
:info:build /usr/include/architecture/ppc/math.h:191: error: storage class specified for parameter ‘__inline_isinff’
:info:build /usr/include/architecture/ppc/math.h:192: error: storage class specified for parameter ‘__inline_isinfd’
:info:build /usr/include/architecture/ppc/math.h:193: error: storage class specified for parameter ‘__inline_isinf’
:info:build /usr/include/architecture/ppc/math.h:194: error: storage class specified for parameter ‘__inline_isnanf’
:info:build /usr/include/architecture/ppc/math.h:195: error: storage class specified for parameter ‘__inline_isnand’
:info:build /usr/include/architecture/ppc/math.h:196: error: storage class specified for parameter ‘__inline_isnan’
:info:build /usr/include/architecture/ppc/math.h:197: error: storage class specified for parameter ‘__inline_isnormalf’
:info:build /usr/include/architecture/ppc/math.h:198: error: storage class specified for parameter ‘__inline_isnormald’
:info:build /usr/include/architecture/ppc/math.h:199: error: storage class specified for parameter ‘__inline_isnormal’
:info:build /usr/include/architecture/ppc/math.h:200: error: storage class specified for parameter ‘__inline_signbitf’
:info:build /usr/include/architecture/ppc/math.h:201: error: storage class specified for parameter ‘__inline_signbitd’
:info:build /usr/include/architecture/ppc/math.h:202: error: storage class specified for parameter ‘__inline_signbit’
:info:build /usr/include/architecture/ppc/math.h:204: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:205: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:206: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:207: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:208: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:209: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:210: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:211: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:212: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:213: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:214: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:215: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:216: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:217: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:218: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
:info:build /usr/include/architecture/ppc/math.h:377: error: storage class specified for parameter ‘acos’
:info:build /usr/include/architecture/ppc/math.h:378: error: storage class specified for parameter ‘acosf’
:info:build /usr/include/architecture/ppc/math.h:380: error: storage class specified for parameter ‘asin’
:info:build /usr/include/architecture/ppc/math.h:381: error: storage class specified for parameter ‘asinf’
:info:build /usr/include/architecture/ppc/math.h:383: error: storage class specified for parameter ‘atan’
:info:build /usr/include/architecture/ppc/math.h:384: error: storage class specified for parameter ‘atanf’
:info:build /usr/include/architecture/ppc/math.h:386: error: storage class specified for parameter ‘atan2’
:info:build /usr/include/architecture/ppc/math.h:387: error: storage class specified for parameter ‘atan2f’
:info:build /usr/include/architecture/ppc/math.h:389: error: storage class specified for parameter ‘cos’
:info:build /usr/include/architecture/ppc/math.h:390: error: storage class specified for parameter ‘cosf’
:info:build /usr/include/architecture/ppc/math.h:392: error: storage class specified for parameter ‘sin’
:info:build /usr/include/architecture/ppc/math.h:393: error: storage class specified for parameter ‘sinf’
:info:build /usr/include/architecture/ppc/math.h:395: error: storage class specified for parameter ‘tan’
:info:build /usr/include/architecture/ppc/math.h:396: error: storage class specified for parameter ‘tanf’
:info:build /usr/include/architecture/ppc/math.h:398: error: storage class specified for parameter ‘acosh’
:info:build /usr/include/architecture/ppc/math.h:399: error: storage class specified for parameter ‘acoshf’
:info:build /usr/include/architecture/ppc/math.h:401: error: storage class specified for parameter ‘asinh’
:info:build /usr/include/architecture/ppc/math.h:402: error: storage class specified for parameter ‘asinhf’
:info:build /usr/include/architecture/ppc/math.h:404: error: storage class specified for parameter ‘atanh’
:info:build /usr/include/architecture/ppc/math.h:405: error: storage class specified for parameter ‘atanhf’
:info:build /usr/include/architecture/ppc/math.h:407: error: storage class specified for parameter ‘cosh’
:info:build /usr/include/architecture/ppc/math.h:408: error: storage class specified for parameter ‘coshf’
:info:build /usr/include/architecture/ppc/math.h:410: error: storage class specified for parameter ‘sinh’
:info:build /usr/include/architecture/ppc/math.h:411: error: storage class specified for parameter ‘sinhf’
:info:build /usr/include/architecture/ppc/math.h:413: error: storage class specified for parameter ‘tanh’
:info:build /usr/include/architecture/ppc/math.h:414: error: storage class specified for parameter ‘tanhf’
:info:build /usr/include/architecture/ppc/math.h:416: error: storage class specified for parameter ‘exp’
:info:build /usr/include/architecture/ppc/math.h:417: error: storage class specified for parameter ‘expf’
:info:build /usr/include/architecture/ppc/math.h:419: error: storage class specified for parameter ‘exp2’
:info:build /usr/include/architecture/ppc/math.h:420: error: storage class specified for parameter ‘exp2f’
:info:build /usr/include/architecture/ppc/math.h:422: error: storage class specified for parameter ‘expm1’
:info:build /usr/include/architecture/ppc/math.h:423: error: storage class specified for parameter ‘expm1f’
:info:build /usr/include/architecture/ppc/math.h:425: error: storage class specified for parameter ‘log’
:info:build /usr/include/architecture/ppc/math.h:426: error: storage class specified for parameter ‘logf’
:info:build /usr/include/architecture/ppc/math.h:428: error: storage class specified for parameter ‘log10’
:info:build /usr/include/architecture/ppc/math.h:429: error: storage class specified for parameter ‘log10f’
:info:build /usr/include/architecture/ppc/math.h:431: error: storage class specified for parameter ‘log2’
:info:build /usr/include/architecture/ppc/math.h:432: error: storage class specified for parameter ‘log2f’
:info:build /usr/include/architecture/ppc/math.h:434: error: storage class specified for parameter ‘log1p’
:info:build /usr/include/architecture/ppc/math.h:435: error: storage class specified for parameter ‘log1pf’
:info:build /usr/include/architecture/ppc/math.h:437: error: storage class specified for parameter ‘logb’
:info:build /usr/include/architecture/ppc/math.h:438: error: storage class specified for parameter ‘logbf’
:info:build /usr/include/architecture/ppc/math.h:440: error: storage class specified for parameter ‘modf’
:info:build /usr/include/architecture/ppc/math.h:441: error: storage class specified for parameter ‘modff’
:info:build /usr/include/architecture/ppc/math.h:443: error: storage class specified for parameter ‘ldexp’
:info:build /usr/include/architecture/ppc/math.h:444: error: storage class specified for parameter ‘ldexpf’
:info:build /usr/include/architecture/ppc/math.h:446: error: storage class specified for parameter ‘frexp’
:info:build /usr/include/architecture/ppc/math.h:447: error: storage class specified for parameter ‘frexpf’
:info:build /usr/include/architecture/ppc/math.h:449: error: storage class specified for parameter ‘ilogb’
:info:build /usr/include/architecture/ppc/math.h:450: error: storage class specified for parameter ‘ilogbf’
:info:build /usr/include/architecture/ppc/math.h:452: error: storage class specified for parameter ‘scalbn’
:info:build /usr/include/architecture/ppc/math.h:453: error: storage class specified for parameter ‘scalbnf’
:info:build /usr/include/architecture/ppc/math.h:455: error: storage class specified for parameter ‘scalbln’
:info:build /usr/include/architecture/ppc/math.h:456: error: storage class specified for parameter ‘scalblnf’
:info:build /usr/include/architecture/ppc/math.h:458: error: storage class specified for parameter ‘fabs’
:info:build /usr/include/architecture/ppc/math.h:459: error: storage class specified for parameter ‘fabsf’
:info:build /usr/include/architecture/ppc/math.h:461: error: storage class specified for parameter ‘cbrt’
:info:build /usr/include/architecture/ppc/math.h:462: error: storage class specified for parameter ‘cbrtf’
:info:build /usr/include/architecture/ppc/math.h:464: error: storage class specified for parameter ‘hypot’
:info:build /usr/include/architecture/ppc/math.h:465: error: storage class specified for parameter ‘hypotf’
:info:build /usr/include/architecture/ppc/math.h:467: error: storage class specified for parameter ‘pow’
:info:build /usr/include/architecture/ppc/math.h:468: error: storage class specified for parameter ‘powf’
:info:build /usr/include/architecture/ppc/math.h:470: error: storage class specified for parameter ‘sqrt’
:info:build /usr/include/architecture/ppc/math.h:471: error: storage class specified for parameter ‘sqrtf’
:info:build /usr/include/architecture/ppc/math.h:473: error: storage class specified for parameter ‘erf’
:info:build /usr/include/architecture/ppc/math.h:474: error: storage class specified for parameter ‘erff’
:info:build /usr/include/architecture/ppc/math.h:476: error: storage class specified for parameter ‘erfc’
:info:build /usr/include/architecture/ppc/math.h:477: error: storage class specified for parameter ‘erfcf’
:info:build /usr/include/architecture/ppc/math.h:479: error: storage class specified for parameter ‘lgamma’
:info:build /usr/include/architecture/ppc/math.h:480: error: storage class specified for parameter ‘lgammaf’
:info:build /usr/include/architecture/ppc/math.h:482: error: storage class specified for parameter ‘tgamma’
:info:build /usr/include/architecture/ppc/math.h:483: error: storage class specified for parameter ‘tgammaf’
:info:build /usr/include/architecture/ppc/math.h:485: error: storage class specified for parameter ‘ceil’
:info:build /usr/include/architecture/ppc/math.h:486: error: storage class specified for parameter ‘ceilf’
:info:build /usr/include/architecture/ppc/math.h:488: error: storage class specified for parameter ‘floor’
:info:build /usr/include/architecture/ppc/math.h:489: error: storage class specified for parameter ‘floorf’
:info:build /usr/include/architecture/ppc/math.h:491: error: storage class specified for parameter ‘nearbyint’
:info:build /usr/include/architecture/ppc/math.h:492: error: storage class specified for parameter ‘nearbyintf’
:info:build /usr/include/architecture/ppc/math.h:494: error: storage class specified for parameter ‘rint’
:info:build /usr/include/architecture/ppc/math.h:495: error: storage class specified for parameter ‘rintf’
:info:build /usr/include/architecture/ppc/math.h:497: error: storage class specified for parameter ‘lrint’
:info:build /usr/include/architecture/ppc/math.h:498: error: storage class specified for parameter ‘lrintf’
:info:build /usr/include/architecture/ppc/math.h:500: error: storage class specified for parameter ‘round’
:info:build /usr/include/architecture/ppc/math.h:501: error: storage class specified for parameter ‘roundf’
:info:build /usr/include/architecture/ppc/math.h:503: error: storage class specified for parameter ‘lround’
:info:build /usr/include/architecture/ppc/math.h:504: error: storage class specified for parameter ‘lroundf’
:info:build /usr/include/architecture/ppc/math.h:508: error: storage class specified for parameter ‘llrint’
:info:build /usr/include/architecture/ppc/math.h:509: error: storage class specified for parameter ‘llrintf’
:info:build /usr/include/architecture/ppc/math.h:511: error: storage class specified for parameter ‘llround’
. . .
```

**Comment by bradh352** [comment]
fixed in 044e6bd

**Comment by sambthompson** [comment]
It looks like this change (or possibly some element of the fix for #783) has broken builds on newer [macOS 10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/237765/steps/install-port/logs/stdio) and [macOS 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/211988/steps/install-port/logs/stdio), as there is now a compile error on `ares_event_configchg.c`:

```
...
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/ares_event_configchg.c:261:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/notify.h:35:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:36:45: error: expected value in expression
#if !defined(HAVE_UNISTD_H) || HAVE_UNISTD_H
                                            ^
1 error generated.

...
```

I'm assuming the patch file MacPorts is carrying from c-ares 1.30 to main branch is a correct reflection of the commits to land fixes for #782/#783.

**Comment by barracuda156** [comment]
@sambthompson The patch is here: https://github.com/macports/macports-ports/blob/716024da0953ba766d759383640212bb0fa63665/net/c-ares/files/patch-fix-build-pre-10.12.diff

I believe, I only removed changed to README, because that file did not exist, so it failed to apply.
I did not modify the code manually anywhere.

**Comment by sambthompson** [comment]
Thanks for clarifying; I had only noted the addition of `#include <fcntl.h>` to `ares_event_configchg.c`. Not sure why there's now breakage on `UNISTD_H` macro guard, but could be unbalanced `#if` vs. `#endif` maybe?

**Comment by barracuda156** [comment]
Maybe it expects to see `#if !defined(HAVE_UNISTD_H) || HAVE_UNISTD_H=0`? But I have no idea why only two specific systems would dislike a macro :)

**Comment by sambthompson** [comment]
> But I have no idea why only two specific systems would dislike a macro :)
Isn't that usually a combination of compiler version and language version? I'm not across C-99 and later versions enough to comment on changes to macro syntax or how boolean evaluation works for `#if`.

**Comment by ryandesign** [comment]
> It looks like this change (or possibly some element of the fix for #783) has broken builds on newer [macOS 10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/237765/steps/install-port/logs/stdio) and [macOS 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/211988/steps/install-port/logs/stdio)

The build on 10.13 and 10.14 was already broken in 1.30.0. Please file a separate issue; it is unrelated to this one.

**Comment by sambthompson** [comment]
> > It looks like this change (or possibly some element of the fix for #783) has broken builds on newer [macOS 10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/237765/steps/install-port/logs/stdio) and [macOS 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/211988/steps/install-port/logs/stdio)
> 
> The build on 10.13 and 10.14 was already broken in 1.30.0. Please file a separate issue; it is unrelated to this one.

Sorry, my recollection was that all builds 10.12 and newer were working (from looking at the [port health](https://ports.macports.org/port/c-ares/details/)) for 1.30.0, before the fixes for #782 and #783 were downstreamed via the patch. This is why the original issue 70207 was filed on MacPorts against 10.11 and older (as well as noting separate issue with 10.7 and earlier that you filed this issue here for).

**Comment by ryandesign** [comment]
From the [builds page](https://ports.macports.org/port/c-ares/builds/) you can see that builds on 10.13 and 10.14 failed on June 16 after the fixes for older systems went in, but also on June 12 when the update to 1.30.0 was first committed.

**Comment by sambthompson** [comment]
> on June 12 when the update to 1.30.0 was first committed.

Wish I had a screen-shot of the port-health screen to check my recollection. Anyway, have now reported the UNISTD_H issue for 10.13 and 10.14 as #787.

**Comment by bradh352** [comment]
please try 5804b30

**Comment by bradh352** [comment]
c-ares 1.31.0 is now out which contains the legacy mac fixes

**Comment by sambthompson** [comment]
> c-ares 1.31.0 is now out which contains the legacy mac fixes

Thanks so much for this, Brad; have opened [update request at MacPorts](https://trac.macports.org/ticket/70246) to update to this new release.
