### ISSUE TITLE
fatal error: 'os/availability.h' file not found building on Mac OS X 10.8 - 10.11

### ISSUE THREAD

**Issue by sambthompson** [c-ares/c-ares#783]
1.30.0 fails to build on [Mac OS X 10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/268051/steps/install-port/logs/stdio):
```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/ares_sysconfig_mac.c:54:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_c-ares/c-ares/work/c-ares-1.30.0/src/lib/thirdparty/apple/dnsinfo.h:31:10: fatal error: 'os/availability.h' file not found
#include <os/availability.h>
         ^
```

There are similar reports for [Mac OS X 10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/181466/steps/install-port/logs/stdio), [Mac OS X 10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/280895/steps/install-port/logs/stdio) and [Mac OS X 10.10](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/273762/steps/install-port/logs/stdio).

It's unclear whether c-ares still supports Mac OS X versions prior to 10.12, given discussion in issue #454, but if it's possible, a fix for this would be appreciated. It may relate to reliance on `clock_gettime`, introduced in 10.12. Discussed at https://trac.macports.org/ticket/70207

**Comment by barracuda156** [comment]
This looks like a wrong header, it should be <AvailabilityMacros.h>.

But the recent version is also broken for other reasons, apparently.

**Comment by barracuda156** [comment]
This is the last version of `configd` using `Availability.h`: https://github.com/apple-oss-distributions/configd/blob/08f6fd8fdfeb9d84264165513f3f1689e0640485/dnsinfo/dnsinfo.h

Should work, perhaps.

**Comment by barracuda156** [comment]
@bradh352 Could you say if the version from `configd` 963.50.8 works or do we need to make a separate fallback for older macOS?

Both `dns_configuration_copy()` and `dns_configuration_free()` are available since 10.4, if that is the only reason to borrow this Apple header, even much earlier SDK will do.

**Comment by bradh352** [comment]
I don't see why we couldn't back off to an earlier version of the dnsinfo.h header.

**Comment by bradh352** [comment]
Can you try the latest 'main', 'v1.30', or 'v1.29' branches to see if this fixes your build issues?

Also, is there a way to test building on old MacOS versions on some CI system?  We're currently using cirrus-ci for MacOS builds and they only support Ventura and Sonoma these days as far as I can tell.

**Comment by sambthompson** [comment]
Not sure if you were asking me, but I can confirm v1.30 builds on 10.11 (El Capitan). Thanks for the lightning response to this report!

**Comment by barracuda156** [comment]
@bradh352 I will try building now and let you know.

Thank you very much for fixing this!

P. S. 1.29.0 was missed, since MacPorts skipped it.

**Comment by barracuda156** [comment]
@bradh352 Build from 45ba9bcfd895d73bbed8f072278f0711d7cbb658 still breaks down:
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:54:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/thirdparty/apple/dnsinfo.h:124: warning: no previous prototype for ‘_dns_configuration_ack’
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/thirdparty/apple/dnsinfo.h: In function ‘_dns_configuration_ack’:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/thirdparty/apple/dnsinfo.h:124: error: expected declaration specifiers before ‘__AVAILABILITY_INTERNAL__MAC_10_8’
[ 85%] Building C object src/lib/CMakeFiles/c-ares.dir/ares_update_servers.c.o
In file included from /usr/include/math.h:26,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:19,
                 from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkConfiguration.h:30,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:55:
/usr/include/architecture/ppc/math.h:65: error: storage class specified for parameter ‘float_t’
/usr/include/architecture/ppc/
```

This is perhaps because `__AVAILABILITY_INTERNAL__MAC_10_8` is not defined before 10.8, unsurprisingly.
(`Availability.h` is an internal header, not supposed to be used by the third-party apps.)

We can either add a define, or switch to `AvailabilityMacros.h`, or remove `_dns_configuration_ack` part since it is unused anyway.

**Comment by barracuda156** [comment]
Ok, this is the issue now:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c: In function ‘read_resolver’:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:156: error: ‘kSCNetworkReachabilityFlagsConnectionOnTraffic’ undeclared (first use in this function)
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:156: error: (Each undeclared identifier is reported only once
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:156: error: for each function it appears in.)
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:266: warning: passing argument 3 of ‘ares__sconfig_append’ with different width due to prototype
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_c-ares/c-ares/work/c-ares-45ba9bcfd895d73bbed8f072278f0711d7cbb658/src/lib/ares_sysconfig_mac.c:266: warning: passing argument 4 of ‘ares__sconfig_append’ with different width due to prototype
make[2]: *** [src/lib/CMakeFiles/c-ares.dir/ares_sysconfig_mac.c.o] Error 1
```

**Comment by barracuda156** [comment]
`kSCNetworkReachabilityFlagsConnectionOnTraffic` is available on 10.6:
https://developer.apple.com/documentation/systemconfiguration/scnetworkreachabilityflags/kscnetworkreachabilityflagsconnectionontraffic

My 10.6 does not have it, apparently, since the SDK is somewhat in-between 10.5 and 10.6.

**Comment by bradh352** [comment]
Apples docs say `kSCNetworkReachabilityFlagsConnectionOnTraffic` is available in 10.6+:

https://developer.apple.com/documentation/systemconfiguration/scnetworkreachabilityflags/kscnetworkreachabilityflagsconnectionondemand?language=objc

Is there a missing header maybe ?

**Comment by bradh352** [comment]
What version of MacOS do we really need to support back to ?

**Comment by barracuda156** [comment]
> What version of MacOS do we really need to support back to ?

I would say 10.5, since it is the last official release to work on PowerPC hardware and the last macOS to work for ppc64.

**Comment by sambthompson** [comment]
> I would say 10.5, since it is the last official release to work on PowerPC hardware and the last macOS to work for ppc64.
While I only use versions as old as 10.11, I can see the argument for PPC support.

**Comment by barracuda156** [comment]
@bradh352 I will test whatever needed locally, this is really important to have working.
(Perhaps no trivial method for CI for macOS ppc, though it is possible to do via Rosetta on an x86 Mac.)

**Comment by barracuda156** [comment]
@catap Kirill, if you could take a look at this, it would be helpful. (There is nothing ppc-specific here, so you could test on x86; as long as we sort out 10.5 and 10.6 on Intel, I can add a fix for 10.6 ppc.)

**Comment by bradh352** [comment]
I'm quite surprised you really support a 15yr old release of MacOS still :)

**Comment by bradh352** [comment]
I also added b08b2e1 as it looks like you also hit some issue including that header.

**Comment by barracuda156** [comment]
Thank you, I will run a build in a few minutes. (The machine is building something now which I cannot interrupt.)

> I'm quite surprised you really support a 15yr old release of MacOS still :)

Not just support, but develop for it too!

(Well, we do not write new software from scratch, admittedly, but I think macOS PowerPC is in a better shape at the moment than it has been for many years, and some important improvements are in the process of making.)

**Comment by barracuda156** [comment]
@bradh352 Awesome, b08b2e169383669edc645ecd95ae34859e9b9f9f builds fine!
Thank you very much.

Could we have a minor release, so that I make a PR to MacPorts with a fix (without having to add extensive patches)?

**Comment by bradh352** [comment]
I could probably push out a point release next week.  Otherwise, you can really just download any updates since the last tag on the release branch like:
https://github.com/c-ares/c-ares/compare/v1.30.0...v1.30.patch

**Comment by barracuda156** [comment]
@bradh352 That works, thanks.

@catap Yeah, I guess so :)

**Comment by barracuda156** [comment]
@bradh352 @catap I am afraid we are not done, in fact. It builds fine now, but does not work, at least if I build `curl` against `c-ares`, I cannot use it:
```
36-198% git push origin master
fatal: unable to access 'https://github.com/barracuda156/macports-ports.git/': Could not resolve host: github.com
```
Activating `c-ares` 1.28.1 fixes the issue without even rebuilding `curl`. So something is not yet right.

**Comment by barracuda156** [comment]
I.e., on the same 10.6 ppc, everything else equal:

`curl` 8.8.0, no `c-ares` – works.
`curl` 8.8.0 linked to `c-ares` 1.28.1 – works.
`curl` 8.8.0 linked to `c-ares` 1.30.0 (plus the patch generated from the link above) – fails to work.

**Comment by barracuda156** [comment]
Let me try `curl` directly also, rather than via `git`. In my example above it is `git` which fails to work, conditional on `curl` being in use.

**Comment by bradh352** [comment]
I'm guessing its something with reading the dns configuration via dns_configuration_copy().  I wonder if its something as basic as not being able to load the symbols from libsystem:
https://github.com/c-ares/c-ares/blob/main/src/lib/ares_sysconfig_mac.c#L106

Since I don't have access to such a system, its really hard for me to speculate.

**Comment by bradh352** [comment]
Also, it would be good to know the oldest MacOS version it *does* work on, like does it work on 10.8?

**Comment by bradh352** [comment]
And you can test with the 'adig' and/or 'ahost' utilities c-ares builds instead of needing to mess with curl for testing just c-ares.

**Comment by bradh352** [comment]
There's an overview here of what is being done: 
https://github.com/c-ares/c-ares/blob/main/src/lib/ares_sysconfig_mac.c#L29

It needs `dns_configuration_copy()` and `dns_configuration_free()`, which are the same symbols as `scutil` and `libresolv` use to retrieve configuration information, but they are unfortunately not in the public headers.

Loading from libSystem we got from Chromium:
https://chromium.googlesource.com/chromium/src/+/HEAD/net/dns/dns_config_watcher_mac.cc#30

**Comment by barracuda156** [comment]
Chromium would have never been tested on any legacy MacOS version, I think. But symbols should be somewhere, they are present in 10.5.8’s `configd`: https://github.com/apple-oss-distributions/configd/blob/ad966faeeb00588090d7b99acb1f581758853da2/dnsinfo/dnsinfo.h#L93-L94

**Comment by bradh352** [comment]
We'd need to identify what library has them on 10.5/10.6.  And like I said, it would be good to know what version the current code works down, I see someone confirmed 10.11 works fine on the macports ticket.

Worst case scenario, we could use 'libresolv' on ancient macos versions probably, but I'd rather not if at all possible just to reduce the amount of code and possibility of regressions in the future.

**Comment by barracuda156** [comment]
Looks like they are in `SystemConfiguration` (but not in `libSystem`):


```
nm -arch ppc -g /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
. . .
0000805c T _dns_configuration_copy
000112d0 T _dns_configuration_free
00003e88 T _dns_configuration_notify_key
```

**Comment by bradh352** [comment]
can you dlopen() a framework ?

**Comment by barracuda156** [comment]
> can you dlopen() a framework ?

I have no idea, but I can replace the path, recompile and see if it works.

**Comment by bradh352** [comment]
`/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration` doesn't even exist on my MacOS Sonoma system, the directory exists but there's no library in there.

**Comment by barracuda156** [comment]
Ok, replacing the path did not work: it compiled (expectedly), but does not work.

**Comment by bradh352** [comment]
can you identify what did not work?  was it the dlopen() or dlsym() ?

**Comment by barracuda156** [comment]
> can you identify what did not work? was it the dlopen() or dlsym() ?

Perhaps the path should be used a bit differently, let me try changing that first. `dlopen` should work with frameworks in principle: https://opensource.apple.com/source/IOKitUser/IOKitUser-502/IOSystemConfiguration.c.auto.html
Though may not work in some cases: https://opensource.apple.com/source/dyld/dyld-195.6/unit-tests/test-cases/dlopen-non-canonical-path/main.c
(Links are not to 10.5–10.6 stuff, but perhaps behavior is similar or same.)

**Comment by barracuda156** [comment]
However, using the following does not fix the problem:
```
dnsinfo->handle = dlopen("/System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration", RTLD_LAZY | RTLD_NOLOAD);
```
What should I do to determine what exactly fails?

**Comment by bradh352** [comment]
Just need to know if dnsinfo->handle is NULL immediately after that dlopen call, you could just add a printf("dlopen failed\n"); in that if statement checking for error below...

its possible that we need to modify dlsym() if the PPC ABI says symbols are prefixed with "_", if its just the dlsym that's failing.

**Comment by barracuda156** [comment]
```
36-198% /opt/local/bin/adig -d 8.8.8.8
dlopen failed

; <<>> c-ares DiG 1.30.0 <<>> 8.8.8.8
;; Timeout while contacting DNS servers
```
Looks like `dlopen` does not work.

**Comment by bradh352** [comment]
can you try dc27e43 ?

**Comment by bradh352** [comment]
wait, hang on ... need another commit

**Comment by bradh352** [comment]
You need dc27e43 and ea6a75c

**Comment by barracuda156** [comment]
Applying dc27e430b3b0240c548951eaccd973e5fd2fc6c1 and ea6a75c1a7c0c4e738602449a3e0b922e857c792 still does not fix the issue, unfortunately.
I will try adding that line to see if dlopen fails or something else.

**Comment by barracuda156** [comment]
```
36-198% /opt/local/bin/adig -d 8.8.8.8
fail 118
fail 128
fail 109

; <<>> c-ares DiG 1.30.0 <<>> 8.8.8.8
;; Timeout while contacting DNS servers
```

From
```
  for (i=0; searchlibs[i] != NULL; i++) {
    dnsinfo->handle = dlopen(searchlibs[i], RTLD_LAZY /* | RTLD_NOLOAD */);
    if (dnsinfo->handle == NULL) {
      printf("fail 109\n");
      /* Fail, loop */
      continue;
    }

    dnsinfo->dns_configuration_copy =
      dlsym(dnsinfo->handle, "dns_configuration_copy");

    if (dnsinfo->dns_configuration_copy == NULL) {
      /* Might be needed for PPC ABI */
      printf("fail 118\n");
      dnsinfo->dns_configuration_copy =
        dlsym(dnsinfo->handle, "_dns_configuration_copy");
    }

    dnsinfo->dns_configuration_free =
      dlsym(dnsinfo->handle, "dns_configuration_free");

    if (dnsinfo->dns_configuration_free == NULL) {
      /* Might be needed for PPC ABI */
      printf("fail 128\n");
      dnsinfo->dns_configuration_free =
        dlsym(dnsinfo->handle, "_dns_configuration_free");
    }

    if (dnsinfo->dns_configuration_copy != NULL &&
        dnsinfo->dns_configuration_free != NULL) {
      break;
    }

    /* Fail, loop */
    dlclose(dnsinfo->handle);
    dnsinfo->handle = NULL;
  }


  if (dnsinfo->dns_configuration_copy == NULL ||
      dnsinfo->dns_configuration_free == NULL) {
    printf("fail 146\n");
    status = ARES_ESERVFAIL;
    goto done;
  }
```

**Comment by bradh352** [comment]
ok, that's interesting, that looks like it succeeded on i == 2 loading the symbols.  Let me simplify then.  It now appears to be failing at a later time.

**Comment by bradh352** [comment]
ef7bffe should simplify it a little to take out stuff that didn't work or wasn't necessary.  Btw are you on IRC anywhere, might be easier to chat.

**Comment by barracuda156** [comment]
Still the same, sadly. I can add printf here and there if that is helpful.

IRC not really, I have the app but never used it. Discord will do?

**Comment by bradh352** [comment]
yeah, i can do discord, where are you?

**Comment by barracuda156** [comment]
> yeah, i can do discord, where are you?

[MacRumors](https://discord.gg/7b9NGb9) server, for example. Or I can join wherever you recommend.

**Comment by bradh352** [comment]
k, just joined that. I'm on as bradh352

**Comment by tobypeterson** [comment]
macOS system libraries are in a shared cache, so the library files won't appear on disk. I believe you're looking for `/usr/lib/system/libsystem_configuration.dylib` - see output of `dyld_info -exports /usr/lib/system/libsystem_configuration.dylib`. However, the symbol most likely already exists since everything links that indirectly via libSystem. You may be able to dlsym it directly (RTLD_DEFAULT), or even call it without using dlsym.

**Comment by bradh352** [comment]
think the current git has the resolution, @barracuda156 was able to test on his PPC machine and it works

**Comment by barracuda156** [comment]
I think it works on 10.8:
```
10:~ svacchanda$ adig 8.8.8.8

; <<>> c-ares DiG 1.30.0 <<>> 8.8.8.8
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50311
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: 0; udp: 4096	
;; QUESTION SECTION:
;8.8.8.8.			IN	A

;; AUTHORITY SECTION:
.		3600	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2024061301 1800 900 604800 86400

;; MSG SIZE  rcvd: 111
```
```
10:~ svacchanda$ port -v installed c-ares
The following ports are currently installed:
  c-ares @1.30.0_1+universal (active) requested_variants='+universal' platform='darwin 12' archs='i386 x86_64' date='2024-06-14T03:52:15+0800'
```

**Comment by bradh352** [comment]
Looks right to me.

Btw, when specifying an ip address, you're likely meaning to use `adig -t PTR 8.8.8.8` for a reverse lookup.  That's why all you got was an SOA record back since the query itself wasn't technically valid.

Otherwise you could do a forward lookup like `adig www.google.com`
