### ISSUE TITLE
Build fails on Ubuntu: getrandom()

### ISSUE THREAD

**Issue by edsiper** [c-ares/c-ares#665]
hi, same as v1.23.0, this version comes with a problem where it fails when building on Ubuntu systems:

```
c-ares-1.24.0/src/lib/ares_rand.c:270:24: error: implicit declaration of function 'getrandom' [-Werror,-Wimplicit-function-declaration]
          ssize_t rv = getrandom(buf + bytes_read, n > 256 ? 256 : n, 0);
```

while integrating the new version in our project the CI triggered the error, more details here:

https://github.com/fluent/fluent-bit/actions/runs/7239437396/job/19721290738?pr=8296#step:5:943

**Comment by bradh352** [comment]
What ubuntu version?  Are you using cmake or autotools?

Can you provide the output of either cmake or autotools so we can see its detection of getrandom()?

We didn't get any report of a failure on c-ares 1.23.  We did, however, receive a failure where getrandom() returned ENOSYS.

**Comment by bradh352** [comment]
please try commit d8edb76 ... it appears the man page says to include sys/random.h but that was never being detected or included, this was a regression introduced by #526 in c-ares 1.20.0.  Its also interesting that when using the latest debian release, it doesn't appear to need sys/random.h for getrandom() support.

**Comment by bradh352** [comment]
actually, i bet your glibc version is less than 2.36 so you don't have arc4random_buf(), which is listed as higher rank than getrandom() in c-ares since its guaranteed to not fail ... https://man7.org/linux/man-pages/man3/arc4random.3.html

**Comment by bradh352** [comment]
I've also added CI tests in #667 for the oldest non-EOL Ubuntu release (20.04LTS) to hopefully catch things like this in the future.  Since that build is succeeding, I'm going to close this as I assume the aforementioned commit probably resolved your issue.

**Comment by edsiper** [comment]
@bradh352 thanks for the quick turnaround. would be there a v1.25 version soon ? thanks

**Comment by bradh352** [comment]
> @bradh352 thanks for the quick turnaround. would be there a v1.25 version soon ? thanks

We've been doing quick releases lately (like every 2-3 weeks) since we've had a lot of new features lately, mostly because I finally left my company and I've had some spare time to work on c-ares :)
