### ISSUE TITLE
c-ares 1.33.1 fails to build with googletest 1.15.2

### ISSUE THREAD

**Issue by dschepler** [c-ares/c-ares#873]
On my machine, trying to build c-ares version 1.33.1 gives compiler errors:
```
In file included from ../../../test/ares-test-mock.cc:26:
../../../test/ares-test.h:799:16: error: expected ‘;’ at end of member declaration
  799 |     static int gtest_registering_dummy_ GTEST_ATTRIBUTE_UNUSED_;               \
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
../../../test/ares-test-mock.cc:836:1: note: in expansion of macro ‘CONTAINED_TEST_P’
  836 | CONTAINED_TEST_P(ContainedMockChannelSysConfig, SysConfigNdotsDefault,
      | ^~~~~~~~~~~~~~~~
../../../test/ares-test.h:799:41: error: ‘GTEST_ATTRIBUTE_UNUSED_’ does not name a type; did you mean ‘GTEST_ATTRIBUTE_PRINTF_’?
  799 |     static int gtest_registering_dummy_ GTEST_ATTRIBUTE_UNUSED_;               \
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
../../../test/ares-test-mock.cc:836:1: note: in expansion of macro ‘CONTAINED_TEST_P’
  836 | CONTAINED_TEST_P(ContainedMockChannelSysConfig, SysConfigNdotsDefault,
      | ^~~~~~~~~~~~~~~~
../../../test/ares-test.h:799:16: error: expected ‘;’ at end of member declaration
  799 |     static int gtest_registering_dummy_ GTEST_ATTRIBUTE_UNUSED_;               \
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
../../../test/ares-test-mock.cc:861:1: note: in expansion of macro ‘CONTAINED_TEST_P’
  861 | CONTAINED_TEST_P(ContainedMockChannelSysConfig, SysConfigNdots0,
      | ^~~~~~~~~~~~~~~~
../../../test/ares-test.h:799:41: error: ‘GTEST_ATTRIBUTE_UNUSED_’ does not name a type; did you mean ‘GTEST_ATTRIBUTE_PRINTF_’?
  799 |     static int gtest_registering_dummy_ GTEST_ATTRIBUTE_UNUSED_;               \
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
../../../test/ares-test-mock.cc:861:1: note: in expansion of macro ‘CONTAINED_TEST_P’
  861 | CONTAINED_TEST_P(ContainedMockChannelSysConfig, SysConfigNdots0,
      | ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1151: arestest-ares-test-mock.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/unfrobbed-dev/pkgs/c-ares/c-ares-1.33.1/debian/obj-amd64/test'
make[1]: *** [Makefile:541: all-recursive] Error 1
make[1]: Leaving directory '/home/unfrobbed-dev/pkgs/c-ares/c-ares-1.33.1/debian/obj-amd64'
```

On the other hand, c-ares version 1.33.0 built successfully with the same version of googletest.

**Comment by bradh352** [comment]
There was a new test added that had to duplicate a huge macro in googletest that appears to change every so often.

**Comment by bradh352** [comment]
any chance you can test out #873 to see if it fixes your issue?

**Comment by dschepler** [comment]
Yes, if I clone that branch then it builds successfully on my system.

**Comment by bradh352** [comment]
Live tests unfortunately depend on behavior of your upstream DNS server, specifically the ANY test a lot of servers disallow.  We typically disable the live tests in our CI/CD systems to prevent failures.
