### ISSUE TITLE
Compile error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Peter-Kahl** [c-ares/c-ares#670]
Most recent commit ... Well, it compiles without errors on my Debian bookworm, but on Ubuntu 20.04 I get this:
```
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in include
make[1]: Entering directory '/var/build-git/c-ares/include'
make  all-am
make[2]: Entering directory '/var/build-git/c-ares/include'
make[2]: Leaving directory '/var/build-git/c-ares/include'
make[1]: Leaving directory '/var/build-git/c-ares/include'
Making all in src
make[1]: Entering directory '/var/build-git/c-ares/src'
Making all in lib
make[2]: Entering directory '/var/build-git/c-ares/src/lib'
make  all-recursive
make[3]: Entering directory '/var/build-git/c-ares/src/lib'
make[4]: Entering directory '/var/build-git/c-ares/src/lib'
  CC       libcares_la-ares__addrinfo2hostent.lo
  CC       libcares_la-ares__addrinfo_localhost.lo
  CC       libcares_la-ares__buf.lo
ares__buf.c: In function ‘ares__buf_append_num_dec’:
ares__buf.c:1017:46: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
 1017 |     status  = ares__buf_append_byte(buf, '0' + (unsigned char)(digit & 0xFF));
      |                                          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__close_sockets.lo
  CC       libcares_la-ares__hosts_file.lo
  CC       libcares_la-ares__htable.lo
  CC       libcares_la-ares__htable_asvp.lo
  CC       libcares_la-ares__htable_strvp.lo
  CC       libcares_la-ares__htable_szvp.lo
  CC       libcares_la-ares__iface_ips.lo
ares__iface_ips.c: In function ‘count_addr_bits’:
ares__iface_ips.c:433:14: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
  433 |     count += ares__count_bits_u8(addr[i]);
      |              ^~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__llist.lo
  CC       libcares_la-ares__parse_into_addrinfo.lo
  CC       libcares_la-ares__read_line.lo
  CC       libcares_la-ares__slist.lo
  CC       libcares_la-ares__socket.lo
ares__socket.c: In function ‘ares__socket_recvfrom’:
ares__socket.c:73:43: error: ‘RECVFROM_TYPE_ARG3’ undeclared (first use in this function); did you mean ‘RECV_TYPE_ARG3’?
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                           ^~~~~~~~~~~~~~~~~~
      |                                           RECV_TYPE_ARG3
ares__socket.c:73:43: note: each undeclared identifier is reported only once for each function it appears in
ares__socket.c:73:62: error: expected ‘)’ before ‘data_len’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                                              ^~~~~~~~
      |                                                              )
ares__socket.c:73:24: error: too few arguments to function ‘recvfrom’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                        ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:269,
                 from ../../include/ares_build.h:100,
                 from ares_setup.h:94,
                 from ares__socket.c:27:
/usr/include/x86_64-linux-gnu/bits/socket2.h:66:1: note: declared here
   66 | recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags,
      | ^~~~~~~~
ares__socket.c:78:1: warning: control reaches end of non-void function [-Wreturn-type]
   78 | }
      | ^
make[4]: *** [Makefile:1013: libcares_la-ares__socket.lo] Error 1
make[4]: Leaving directory '/var/build-git/c-ares/src/lib'
make[3]: *** [Makefile:1452: all-recursive] Error 1
make[3]: Leaving directory '/var/build-git/c-ares/src/lib'
make[2]: *** [Makefile:714: all] Error 2
make[2]: Leaving directory '/var/build-git/c-ares/src/lib'
make[1]: *** [Makefile:408: all-recursive] Error 1
make[1]: Leaving directory '/var/build-git/c-ares/src'
make: *** [Makefile:529: all-recursive] Error 1
```

**Comment by bradh352** [comment]
Are you using autotools or cmake?

We have our CI building on Ubuntu 20.04 for both, and they appear to work:
* CMake: https://cirrus-ci.com/task/5067678709186560
* Autotools: https://cirrus-ci.com/task/6193578616029184

**Comment by bradh352** [comment]
looks like you're using autotools based on the very top of your log (config.status).  Can you find this line in the output:
```checking types of args and return type for recvfrom... int,void *,size_t,int,struct sockaddr *,socklen_t *,ssize_t```
That's what determines and sets that.

**Comment by jurisuk** [comment]
Autotools.
```
checking types of args and return type for recvfrom ... unknown
```

**Comment by bradh352** [comment]
well, that's definitely an issue. 
Can you re-run: `autoreconf -fi` and make sure that doesn't fail.  Then re-run configure and see if anything improves.

**Comment by jurisuk** [comment]
That's how I ran it, ```autoreconf -fi```.

And BTW:
```
Cloning into 'c-ares'...
remote: Enumerating objects: 13358, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 13358 (delta 90), reused 103 (delta 66), pack-reused 13205
Receiving objects: 100% (13358/13358), 6.82 MiB | 7.56 MiB/s, done.
Resolving deltas: 100% (8915/8915), done.
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, '../m4'.
libtoolize: copying file '../m4/libtool.m4'
libtoolize: copying file '../m4/ltoptions.m4'
libtoolize: copying file '../m4/ltsugar.m4'
libtoolize: copying file '../m4/ltversion.m4'
libtoolize: copying file '../m4/lt~obsolete.m4'
configure.ac:35: installing './compile'
configure.ac:35: installing './config.guess'
configure.ac:35: installing './config.sub'
configure.ac:26: installing './install-sh'
configure.ac:26: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Remember to add 'LT_INIT' to configure.ac.
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:135: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:135: the top level
configure.ac:129: installing './compile'
```

**Comment by bradh352** [comment]
And attempting configure again after that doesn't fix anything?  If so, I'm really not sure since our CI test on ubuntu 20.04 works as intended and also does the `autoreconf -fi`.  Are you chain building with another project?  If so, perhaps its interfering somehow.  Honestly, I'm more of a CMake person, I find it really hard to debug autotools issues.  Maybe look in config.log to see if there is a smoking gun around the recvfrom() detection?

**Comment by jurisuk** [comment]
Thanks for trying to help.
I have been running the same script compiling c-ares on nearly daily bais for more than 2 years and it always worked, until now.
Anyways, please close this. I'll figure it out. All the best!

**Comment by bradh352** [comment]
I don't know if it will do any good, but I just committed some changes to resolve some autotools warnings during autoreconf.

**Comment by freebendy** [comment]
I got the same error while I was building `main` and `cares-1_24_0` on Ubuntu 20.04.6 LTS.

`./configure` show the following:
```
checking types of args and return type for recv... int,void *,size_t,int,ssize_t
checking for sys/types.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for recvfrom... yes
checking types of args and return type for recvfrom... unknown
configure: WARNING: Cannot find proper types to use for recvfrom args
```

**Comment by bradh352** [comment]
You got this on the latest `main` after my 1e34608 commit as well?  Can you supply your config.log?  It might have a smoking gun in there ... especially since `recv` detection works, `recvfrom` is basically identical.  What's really interesting is this autotools logic hasn't changed in years so I can't really understand how it would crop up now, especially since our explicit testing on ubuntu 20.04 works flawlessly.  Is your system fully up to date on all packages?  Are you using any 3rd party repos or backports (say, updated compilers or anything)?

**Comment by dfandrich** [comment]
I can reproduce this on current main using this Dockerfile:

```Dockerfile
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y gcc make automake autoconf libtool git pkg-config libgmock-dev
RUN git clone --depth 10 https://github.com/c-ares/c-ares.git
RUN cd c-ares && autoreconf -sif && ./configure --prefix /install && make -j6 && make -j6 test && make install
```
The issue seems to be that the glibc 2.31-0ubuntu9.14 `recvfrom()` declaration includes some `__restrict` attributes, plus there's an inline definition available, which is (after macro expansion):

```C
extern __inline __attribute__ ((__always_inline__)) __attribute__ ((__gnu_inline__)) __attribute__ ((__artificial__)) ssize_t
recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags,
   struct sockaddr *__restrict __addr, socklen_t *__restrict __addr_len)
{
...
}
```
This isn't among the 1440 different permutations of `recvfrom()` signatures tried by configure. The `__restrict` keywords cause `error: conflicting types for 'recvfrom'` and `__always_inline__`  causes:

     /usr/include/x86_64-linux-gnu/bits/socket2.h:64:1: error: inlining failed in call to always_inline 'recvfrom': mismatched arguments

Even after adding `__restrict` versions of those three arguments to the test (bringing the total permutations to 3456), the `__always_inline` still causes a failure.

The `recv()` declaration doesn't contain any `__restrict` keywords and it doesn't suffer the same fate. It *does* have the `__always_inline` and an inline definition, so I'm not sure why it doesn't also result in an "inlining failed" error; maybe the presence of `__restrict` affects that.

I'm not sure how to fix this, nor why it doesn't affect glibc 2.32, which has substantially the same definitions. I suspect gcc has been changed so that the presence or absence of `__restrict` is no longer considered when comparing definitions. The `__always_inline` issue looks very much like a compiler bug to me, because after my test of adding `__restrict` to the argument definitions attempted by configure, the definition tried was identical. The 20.04 gcc is 9.4.0 and the one I tried with glibc 2.32 is 10.4.0.

One workaround for Ubuntu 20.04 is to use clang instead of gcc, which works as expected.

**Comment by bradh352** [comment]
Thanks for the detailed explanation.  That said, is there any reason you can come up with that our CI build is working on Ubuntu 20.04? I mean what you showed for importing the dockerfile and installing the deps, it looks substantially similar.  Our CI system does add `--disable-symbol-hiding --enable-expose-statics --enable-maintainer-mode --enable-debug` to configure, not sure if any of those are conflicting.

That said, I really do dislike the way c-ares detects the parameter types with autotools.  In CMake we just make some educated guesses and its worked out pretty well.

**Comment by bagder** [comment]
> I really do dislike the way c-ares detects the parameter types with autotools

Agreed. It was always overly zealous. In curl we moved away from that approach, because as you say it is unnecessary and slow. (I believe this style was introduced into both curl and c-ares at around the same time)

**Comment by dfandrich** [comment]
Adding the `--enable-debug` option fixes the compile. This translates into adding the `-O0` and `-g` options to gcc and that makes the difference. For one, it eliminates the inline function definition, and seemingly causes the `__restrict` difference to be ignored as well. `./configure CFLAGS=-O0` fixes it as well.

**Comment by bradh352** [comment]
very interesting. I'll see what I can do to rework the autotools configure stuff, but that may take a while.  Honestly, if possible, I'd recommend using CMake these days.

**Comment by bradh352** [comment]
starting work on it in PR #674

**Comment by bradh352** [comment]
I think PR #674 is basically done if someone having issues on Ubuntu 20.04 wants to give it a try

**Comment by dfandrich** [comment]
I haven't looked at the changes in PR #674, but Ubuntu 20.04 compiles fine now with them in place. There are 118 test failures, however.

**Comment by bradh352** [comment]
@dfandrich can you share the test failures?  If they're "live" tests, that may be expected based on your system's configuration.

**Comment by bradh352** [comment]
@dfandrich our ubuntu 20.04 tests here: https://api.cirrus-ci.com/v1/task/6118081336967168/logs/main.log


404 tests passed, 0 failures.

Its typically run with `./arestest -4 -v --gtest_filter=-*LiveSearchTXT*:*LiveSearchANY*` in our CI environment due to known environmental issues that can crop up.  We might be able to get rid of "-4" these days though as I think most environments have working ipv6 these days.

**Comment by jurisuk** [comment]
PR https://github.com/c-ares/c-ares/pull/674 fails compiling on Ubuntu 20.04.
```
checking for recvfrom... yes
checking types of args and return type for recvfrom... unknown
configure: WARNING: Cannot find proper types to use for recvfrom args
.......
=== configuring in test (/var/build-git2/c-ares/test)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
......
make[4]: Entering directory '/var/build-git2/c-ares/src/lib'
  CC       libcares_la-ares__addrinfo2hostent.lo
  CC       libcares_la-ares__addrinfo_localhost.lo
  CC       libcares_la-ares__buf.lo
ares__buf.c: In function ‘ares__buf_append_num_dec’:
ares__buf.c:1051:46: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
 1051 |     status  = ares__buf_append_byte(buf, '0' + (unsigned char)(digit & 0xFF));
      |                                          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__close_sockets.lo
  CC       libcares_la-ares__hosts_file.lo
  CC       libcares_la-ares__htable.lo
  CC       libcares_la-ares__htable_asvp.lo
  CC       libcares_la-ares__htable_strvp.lo
  CC       libcares_la-ares__htable_szvp.lo
  CC       libcares_la-ares__iface_ips.lo
ares__iface_ips.c: In function ‘count_addr_bits’:
ares__iface_ips.c:432:14: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
  432 |     count += ares__count_bits_u8(addr[i]);
      |              ^~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__llist.lo
  CC       libcares_la-ares__parse_into_addrinfo.lo
  CC       libcares_la-ares__read_line.lo
  CC       libcares_la-ares__slist.lo
  CC       libcares_la-ares__socket.lo
ares__socket.c: In function ‘ares__socket_recvfrom’:
ares__socket.c:73:43: error: ‘RECVFROM_TYPE_ARG3’ undeclared (first use in this function); did you mean ‘RECV_TYPE_ARG3’?
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                           ^~~~~~~~~~~~~~~~~~
      |                                           RECV_TYPE_ARG3
ares__socket.c:73:43: note: each undeclared identifier is reported only once for each function it appears in
ares__socket.c:73:62: error: expected ‘)’ before ‘data_len’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                                              ^~~~~~~~
      |                                                              )
ares__socket.c:73:24: error: too few arguments to function ‘recvfrom’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                        ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:269,
                 from ../../include/ares_build.h:100,
                 from ares_setup.h:94,
                 from ares__socket.c:27:
/usr/include/x86_64-linux-gnu/bits/socket2.h:66:1: note: declared here
   66 | recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags,
      | ^~~~~~~~
ares__socket.c:78:1: warning: control reaches end of non-void function [-Wreturn-type]
   78 | }
      | ^
make[4]: *** [Makefile:1013: libcares_la-ares__socket.lo] Error 1
make[4]: Leaving directory '/var/build-git2/c-ares/src/lib'
make[3]: *** [Makefile:1452: all-recursive] Error 1
make[3]: Leaving directory '/var/build-git2/c-ares/src/lib'
make[2]: *** [Makefile:714: all] Error 2
make[2]: Leaving directory '/var/build-git2/c-ares/src/lib'
make[1]: *** [Makefile:408: all-recursive] Error 1
make[1]: Leaving directory '/var/build-git2/c-ares/src'
make: *** [Makefile:529: all-recursive] Error 1
```

**Comment by bradh352** [comment]
@jurisuk you're definitely not building from #674 with the output you provided.  You'll never see `checking types of args and return type for recvfrom...` in the configure output if you're using #674 as that is gone.

**Comment by jurisuk** [comment]
@bradh352 right you are!
OTOH, building from #674 fails also:
```
make[4]: Entering directory '/var/build-git/c-ares/src/lib'
  CC       libcares_la-ares__addrinfo2hostent.lo
  CC       libcares_la-ares__addrinfo_localhost.lo
  CC       libcares_la-ares__buf.lo
ares__buf.c: In function ‘ares__buf_append_num_dec’:
ares__buf.c:1051:46: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
 1051 |     status  = ares__buf_append_byte(buf, '0' + (unsigned char)(digit & 0xFF));
      |                                          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__close_sockets.lo
  CC       libcares_la-ares__hosts_file.lo
  CC       libcares_la-ares__htable.lo
  CC       libcares_la-ares__htable_asvp.lo
  CC       libcares_la-ares__htable_strvp.lo
  CC       libcares_la-ares__htable_szvp.lo
  CC       libcares_la-ares__iface_ips.lo
ares__iface_ips.c: In function ‘count_addr_bits’:
ares__iface_ips.c:432:14: warning: conversion from ‘int’ to ‘unsigned char’ may change value [-Wconversion]
  432 |     count += ares__count_bits_u8(addr[i]);
      |              ^~~~~~~~~~~~~~~~~~~
  CC       libcares_la-ares__llist.lo
  CC       libcares_la-ares__parse_into_addrinfo.lo
  CC       libcares_la-ares__read_line.lo
  CC       libcares_la-ares__slist.lo
  CC       libcares_la-ares__socket.lo
ares__socket.c: In function ‘ares__socket_recvfrom’:
ares__socket.c:73:43: error: ‘RECVFROM_TYPE_ARG3’ undeclared (first use in this function); did you mean ‘RECV_TYPE_ARG3’?
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                           ^~~~~~~~~~~~~~~~~~
      |                                           RECV_TYPE_ARG3
ares__socket.c:73:43: note: each undeclared identifier is reported only once for each function it appears in
ares__socket.c:73:62: error: expected ‘)’ before ‘data_len’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                                                              ^~~~~~~~
      |                                                              )
ares__socket.c:73:24: error: too few arguments to function ‘recvfrom’
   73 |   return (ares_ssize_t)recvfrom(s, data, (RECVFROM_TYPE_ARG3)data_len, flags,
      |                        ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:269,
                 from ../../include/ares_build.h:100,
                 from ares_setup.h:94,
                 from ares__socket.c:27:
/usr/include/x86_64-linux-gnu/bits/socket2.h:66:1: note: declared here
   66 | recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags,
      | ^~~~~~~~
ares__socket.c:78:1: warning: control reaches end of non-void function [-Wreturn-type]
   78 | }
      | ^
make[4]: *** [Makefile:1013: libcares_la-ares__socket.lo] Error 1
make[4]: Leaving directory '/var/build-git/c-ares/src/lib'
make[3]: *** [Makefile:1452: all-recursive] Error 1
make[3]: Leaving directory '/var/build-git/c-ares/src/lib'
make[2]: *** [Makefile:714: all] Error 2
make[2]: Leaving directory '/var/build-git/c-ares/src/lib'
make[1]: *** [Makefile:408: all-recursive] Error 1
make[1]: Leaving directory '/var/build-git/c-ares/src'
make: *** [Makefile:529: all-recursive] Error 1
```

**Comment by bradh352** [comment]
@jurisuk pretty sure this would be the same issue, you're really not on #674.  Its not possible for RECVFROM_TYPE_ARG3 to not be defined.  It can be defined to the wrong thing, but being undefined, nope, you're not using #674 if your'e getting that.  (Or maybe you didn't re-run autoreconf -fi )

**Comment by bradh352** [comment]
I'm not sure how to clone a PR directly with git, but you can just clone my fork with the branch `autotools_rework`:
```
git clone -b autotools_rework https://github.com/bradh352/c-ares.git c-ares-autotools-rework
```

**Comment by jurisuk** [comment]
Disregard my last two posts above.
Brad's fix works! 👏🏻👏🏻

**Comment by dfandrich** [comment]
The `make check` output [is here](https://gist.github.com/dfandrich/6f9feb810e8be7a778489d9b54cfdbdf) (N.B. this was on a machine without IPv6 connectivity). Running that `./arestest` line you provide ended successfully with `[  PASSED  ] 378 tests.`.

**Comment by bradh352** [comment]
@dfandrich great, makes sense then
