### ISSUE TITLE
c-ares 1.34.5 fails to build with GCC 15.1.0 due to missing `errno.h` includes

### ISSUE THREAD

**Issue by dholm** [c-ares/c-ares#990]
Hi,
I'm trying to build c-ares `1.34.5` using GCC `15.1.0` on GNU/Linux but it's failing due to that a lot of files are referring to `errno` but without including `errno.h`.

``` text
src/lib/inet_ntop.c: In function 'ares_inet_ntop':                                   
src/lib/inet_ntop.c:45:29: error: 'errno' undeclared (first use in this function)    
   45 | #  define SET_SOCKERRNO(x) (errno = (x))
      |                             ^~~~~
src/lib/inet_ntop.c:75:3: note: in expansion of macro 'SET_SOCKERRNO'                
   75 |   SET_SOCKERRNO(EAFNOSUPPORT);
      |   ^~~~~~~~~~~~~                                             
src/lib/inet_ntop.c:30:1: note: 'errno' is defined in header '<errno.h>'; this is probably fixable by adding '#include <errno.h>'
   29 | #include "ares_nameser.h"                                   
  +++ |+#include <errno.h>                                          
   30 | #include "ares_ipv6.h"                                      
src/lib/inet_ntop.c:45:29: note: each undeclared identifier is reported only once for each function it appears in
   45 | #  define SET_SOCKERRNO(x) (errno = (x))
      |                             ^~~~~
```

By including `errno.h` in `src/lib/ares_socket.h` all of the errors during my build went away but since that header does not include anything today I'm not sure if that is the appropriate solution so I did not prepare a pull request.

**Comment by bradh352** [comment]
thanks for the report, I'll take a look at it.  Interesting its not showing up in our CI autobuilds across various linux distributions.

**Comment by fivemeyestore** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by fivemhostingserver** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by myeyestore** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by eyesgodcode** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by eyesaider** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by godofcodeeyes** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by fivemserverhostings** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by eyestorefivem** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by fivemservereyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by fivemeyestoreserver** [comment]
I'm impressed by the modularity of this codebase. Makes it very maintainable.

**Comment by ayestoro** [comment]
I'm impressed by the modularity of this codebase. Makes it very maintainable.

**Comment by bradh352** [comment]
I looked into this and I think this may be something wrong with when you ran configure or cmake.  If HAVE_ERRNO_H gets defined, ares_setup.h includes errno.h.  ares_setup.h is included as the _**first**_ file by ares_private.h which is the _**first**_ file included in inet_ntop.c

Also none of our CI tooling exhibits the same behavior.

If you can provide more information on how to reproduce this and output of your configure or cmake calls it would be helpful.

**Comment by bradh352** [comment]
Can't reproduce.  Added a Fedora CI build that has GCC 15 as I realized none of the other builds were yet on GCC 15.  It built using both Autotools and CMake ... all looks good.   Going to close this.  Reopen if more information can be provided on how to reproduce, but looking at the code as I previously did it appeared that for whatever reason errno.h must not have been detected as available on your platform.
