### ISSUE TITLE
c-ares 1.34.5 does not build with gtest 1.17.0

### ISSUE THREAD

**Issue by fundawang** [c-ares/c-ares#993]
It seems that c-ares 1.34.5 is forcing c++14 which is not supported by gtest 1.17.0
```
2025-05-13 16:44:12 g++ -std=c++14 -DHAVE_CONFIG_H   -I../include -I../src/lib -I../include -I../src/lib -I../src/lib/include -I../test -I../test -I.. -DCARES_NO_DEPRECATED  -pthread -DGTEST_HAS_PTHREAD=1 -O2 -flto=auto -ffat-lto-objects -g -grecord-gcc-switches -pipe -fstack-protector-strong  -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/generic-hardened-cc1 -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fexceptions -c -o arestest-ares-test-parse-caa.o `test -f 'ares-test-parse-caa.cc' || echo './'`ares-test-parse-caa.cc
2025-05-13 16:44:12 make[1]: Leaving directory '/home/lkp/rpmbuild/BUILD/c-ares-1.34.5/test'
2025-05-13 16:44:12 In file included from /usr/include/gtest/gtest-message.h:57,
2025-05-13 16:44:12                  from /usr/include/gtest/gtest-assertion-result.h:46,
2025-05-13 16:44:12                  from /usr/include/gtest/gtest.h:63,
2025-05-13 16:44:12                  from ares-test.h:35,
2025-05-13 16:44:12                  from ares-test-parse-caa.cc:26:
2025-05-13 16:44:12 /usr/include/gtest/internal/gtest-port.h:273:2: error: #error C++ versions less than C++17 are not supported.
2025-05-13 16:44:12   273 | #error C++ versions less than C++17 are not supported.
```

**Comment by bradh352** [comment]
Fixed in PR #1004
